In [2]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# set a path variable to the directory containing raman covid data:. ../raw_data/Raman_Covid
path = '../raw_data/Raman_Covid'
# Concatenate directory path to the file name: covid_path
covid_path = path + '/covid_and_healthy_spectra.csv'
# Load data file to a dataframe: covid_data
covid_data = pd.read_csv(covid_path)

In [24]:
#Use pandas' Series method `value_counts` to find any duplicated resort names
#covid_data['diagnostic'].value_counts().head()
#covid = covid_data.iloc[:,:-1]
healthy = covid_data[covid_data['diagnostic'] == 'Healthy']
#print(len(covid))
print(len(healthy))
covid = covid_data[covid_data['diagnostic'] == 'SARS-CoV-2']
print(len(covid))
healthy.T.head()

150
159

,0,1,2,3,4,5,6,7,8,9,...,140,141,142,143,144,145,146,147,148,149
400,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
402,-0.015237,-0.0120981,-0.0129999,-0.0157281,-0.0203548,-0.0237458,-0.0217384,-0.0209203,-0.0223649,-0.0124614,...,-0.0192883,-0.0116069,-0.0143301,-0.0113812,-0.0154852,-0.0175054,-0.0214325,-0.00747744,-0.00826969,-0.011745
405,-0.0306067,-0.028164,-0.0290584,-0.034346,-0.0458387,-0.0532674,-0.0433915,-0.0441161,-0.0432127,-0.0259161,...,-0.0400226,-0.0275599,-0.0301321,-0.0271344,-0.0306613,-0.0341123,-0.0480678,-0.0196857,-0.0203973,-0.024329
407,-0.0383089,-0.0351893,-0.0350211,-0.0451402,-0.0605559,-0.0688812,-0.0552412,-0.0552365,-0.0539728,-0.0346382,...,-0.0519988,-0.0353761,-0.0384504,-0.0349241,-0.0384586,-0.0418588,-0.0617158,-0.0230259,-0.0249455,-0.0291233
410,-0.0390776,-0.0361379,-0.0349939,-0.0476712,-0.0658055,-0.073029,-0.060167,-0.0579549,-0.056038,-0.0339743,...,-0.0578134,-0.036555,-0.0393772,-0.0366812,-0.0387323,-0.0452196,-0.0633211,-0.0222106,-0.0230743,-0.0295311

In [22]:
X = list(map(float, covid_data.columns.values[0:900]))

In [ ]:
DataFrame.sample(n=10, frac=None, replace=False, weights=None, random_state=None, axis=None)

In [7]:
def build_profile(first, last, **user_info):
    """Build a user's profile dictionary."""
# Build a dict with the required keys.
    profile = {'first': first, 'last': last}
 # Add any other keys and values.
    for key, value in user_info.items():
         profile[key] = value
    return profile
# Create two users with different kinds
# of information.
user_0 = build_profile('albert', 'einstein',
 location='princeton')
user_1 = build_profile('marie', 'curie',
 location='paris', field='chemistry')
print(user_0)
print(user_1)

{'first': 'albert', 'last': 'einstein', 'location': 'princeton'}
{'first': 'marie', 'last': 'curie', 'location': 'paris', 'field': 'chemistry'}